### ISSUE TITLE
Does not match multimarkdown syntax

### ISSUE THREAD

**Issue by konobi** [chrisjaure/metamd#4]
Hey there,

The multimarkdown format defines that metadata lives up at the top of the file. I attempted to do so, but the meta data appears in the rendered body. If I add equal signs to the top, or a newline before the equal signs, they will also appear in the rendered body. It would be great to have it match the multimarkdown format.

**Comment by chrisjaure** [comment]
Wow, github didn't tell me about this issue :(

Anyway, I'll take a look at implementing compatibility with multimarkdown. Hadn't heard of it before.

**Comment by chrisjaure** [comment]
Fixed in 51077fd39159ccb8313ea973c57e28cc86451010
